[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.10"
gas_reports = ["Registrar", "NftAuthoriser", "GatewayBeta"]

[doc]
out = "docs"
title = "me3 Subdomain Registrar"
book = "./book.toml"
ignore = ["./test/*.t.sol"]
