[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.10"
gas_reports = ["Registrar", "NftAuthoriser", "GatewayBeta"]
memory_limit = 43554432

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

[doc]
out = "docs"
title = "me3 Subdomain Registrar"
book = "./book.toml"
ignore = ["./test/*.t.sol"]
