on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

name: Publish ABIs

jobs:
  publisher:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts
        run: forge build
        env:
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          ENS_REGISTRY: "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        run: echo "Version published: ${{ steps.publish.outputs.version }}"

      - if: steps.publish.outputs.type == 'none'
        run: echo "Failed to publish"
